---
- name: Install nginx web server
  apt:
    name: nginx
    state: latest
    force: yes
    autoremove: yes
    autoclean: yes
  tags: master

- name: add APK mime-type for nginx
  lineinfile:
    path: /etc/nginx/mime.types
    line: '    application/vnd.android.package-archive apk;'
    state: present
  tags: master

- name: install 502.html
  template:
    src: 502.html.j2
    dest: /var/www/502.html
  tags: ['master', 'rename']

- name: install 404.html
  template:
    src: 404.html.j2
    dest: /var/www/404.html
  tags: ['master', 'rename']

- name: install version.html
  template:
    src: version.html.j2
    dest: /var/www/version.html
  tags: ['master', 'rename']

- name: install version rewriter script
  copy:
    src: rewrite_version_html.py
    dest: /usr/local/bin/rewrite_version_html.py
    mode: 0755
  tags: master

- name: add version rewriter script to startup
  cron:
    name: "Check raspberryPi version on boot"
    special_time: reboot
    job: "/usr/local/bin/rewrite_version_html.py"
    state: present
  tags: master

- name: Remove default nginx vhost config file (if configured).
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags: master

- name: Upload nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: restart nginx
  tags: master

- name: install welcome redirect
  template:
    src: welcome.j2
    dest: /etc/nginx/sites-enabled/welcome
  tags: ['master', 'rename']


- name: install version vhost
  template:
    src: version.j2
    dest: /etc/nginx/sites-enabled/version
  tags: ['master', 'rename']

- name: install default placeholder vhost for services
  template:
    src: placeholder.j2
    dest: /etc/nginx/sites-enabled/{{ item.name }}
  with_items:
    - { name: 'edupi', fqdn: "{{ edupi_fqdn }}" }
    - { name: 'kalite', fqdn: "{{ kalite_fqdn }}" }
    - { name: 'aflatoun', fqdn: "{{ aflatoun_fqdn }}" }
    - { name: 'fr.wikifundi', fqdn: "fr.{{ wikifundi_fqdn }}" }
    - { name: 'en.wikifundi', fqdn: "en.{{ wikifundi_fqdn }}" }
  tags: master
