#!/usr/bin/env python
# -*- coding: utf-8 -*-

import socket


def is_connected(host="1.1.1.1"):
    try:
        socket.create_connection((host, 53), timeout=4)
        return True
    except Exception:
        pass
    return False


if __name__ == "__main__":
    print("yes" if is_connected() else "no")
