---
- name: Ensure directory exists
  file:
    path: "{{ africatikmd_root }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: ['master', 'reconfigure']

- name: Ensure apps directory exists
  file:
    path: "{{ africatikmd_content_path }}"
    state: directory
  tags: ['master', 'reconfigure', 'content']

- name: install nginx vhost
  template:
    src: nginx.vhost.j2
    dest: /etc/nginx/sites-available/africatikmd
    mode: 0644
  tags: ['master', 'rename', 'reconfigure']

- name: enable africatik vhost
  file:
    src: /etc/nginx/sites-available/africatikmd
    dest: /etc/nginx/sites-enabled/africatikmd
    state: link
    force: yes
  notify: restart nginx
  tags: ['master', 'reconfigure']

- name: Copy static files
  copy:
    src: static
    dest: "{{ africatikmd_root }}/"
  tags: ['master', 'reconfigure']

- name: copy page
  template:
    src: index.html.j2
    dest: "{{ africatikmd_root }}/index.html"
    mode: 0644
  tags: ['master', 'reconfigure']
