---
- name: prevent kernel from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - raspberrypi-kernel
    - raspberrypi-bootloader
  tags: master

- name: remove resize_fs from first boot
  replace:
    path: /boot/cmdline.txt
    regexp: ' init=/usr/lib/raspi-config/init_resize.sh'
    replace: ''
    backup: no
  tags: master

- name: Remove udev rules for wifi
  file:
    path: /etc/udev/rules.d/70-persistent-net.rules
    state: absent
  tags: master

- name: reload udev
  shell: udevadm control --reload-rules && udevadm trigger
  tags: master

- name: add exfat module to startup list
  lineinfile:
    dest: /etc/modules-load.d/modules.conf
    line: exfat
    state: present
  tags: master

- name: check if exfat is already loaded
  shell: cat /proc/filesystems |grep exfat | wc -l
  register: has_exfat
  tags: master

- name: load exfat module for current run
  command: modprobe exfat
  when: has_exfat.stdout.strip()|int == 0
  tags: master

- name: create systemd-service to ublock RF on start
  copy:
    src: unblock-rf.service
    dest: /etc/systemd/system/unblock-rf.service
  tags: master

- name: reload systemd
  command: systemctl daemon-reload
  tags: master

- name: Run apt update
  apt:
    update_cache: yes
  tags: ['master', 'setup']

- name: Fix broken package
  shell: dpkg --configure -a
  tags: master

- name: Install or upgrade all required package
  apt:
    name: python-dev,git,locate,ntpdate,fake-hwclock,ncurses-term,libffi-dev,libssl-dev,screen,iftop,libwww-perl,sqlite3,apt-transport-https,exfat-utils,python3-pip,python3-setuptools,python-pip,python-setuptools
    state: latest
    autoremove: yes
    autoclean: yes
  tags: master

- name: remove exfat-fuse
  apt:
    name: exfat-fuse
    state: absent
    autoremove: yes
    autoclean: yes
  tags: master

- import_tasks: clean_apt.yml
  tags: master

- name: Upgrade pip and virtualenv for python{{ python3_version }}
  command: python{{ python3_version }} -m pip install -U virtualenv
  tags: master

- name: Drop hosts file on device
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags: ['master', 'rename']

- name: Create a {{ group }} group on the system
  group:
    name: "{{ group }}"
    state: present
  tags: master

- name: Create an {{ username }} user on the system
  user:
    name: "{{ username }}"
    shell: /bin/bash
    group: "{{ group }}"
    groups: "sudo,www-data,adm,staff"
    home: "/home/{{ username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    password: "{{ password }}"
    update_password: 'on_create'
  tags: master

- name: Add locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - fr_FR.UTF-8
    - en_US.UTF-8
  tags: master

- name: set default locale to en_US
  copy:
    src: locale
    dest: /etc/default/locale
    mode: 0644
  tags: master

- name: Copy a blank rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags: master

- name: Copy .bashrc for root
  copy:
    src: bashrc
    dest: /root/.bashrc
    owner: root
  tags: master

- name: Copy the global vimrc file
  copy:
    src: vimrc.local
    dest: /etc/vim/vimrc.local
    owner: root
    mode: 0644
  tags: master

- name: Copy .bashrc for new username
  copy:
    src: bashrc
    dest: /home/{{ username }}/.bashrc
    owner: "{{ username }}"
  tags: master

- name: Copy visudo file for {{username}} user
  template:
    src: visudo.j2
    dest: /etc/sudoers.d/shutdown
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
  tags: master

- name: Create/chmod local directory to work from
  file:
    path: /var/lib/ansible/local
    state: directory
    owner: root
    group: root
    mode: 0751
  tags: master

- name: Create ansible hosts directory to work from
  file:
    path: /etc/ansible/
    state: directory
    owner: root
    group: root
    mode: 0751
  tags: master

- name: Copy ansible inventory file to client
  copy:
    src: hosts
    dest: /etc/ansible/hosts
    owner: root
    group: root
    mode: 0644
  tags: master

- name: Remove the existing localtime file
  file:
    path: /etc/localtime
    state: absent
  tags: ['master', 'setup', 'reconfigure']

- name: Set a new localtime file corresponding to the timezone
  file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link
    force: yes
  tags: ['master', 'setup', 'reconfigure']

- name: Set timezone variables
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: update timezone
  tags: ['master', 'setup', 'reconfigure']

- name: add rfkill unblock to startup
  cron:
    name: "Unblock RF devices"
    special_time: reboot
    job: "/usr/sbin/rfkill unblock all"
    state: present
  tags: master

- name: Checking if grub conf file is there
  stat:
    path: /etc/default/grub
  register: is_grub
  tags: master

- name: Shorten GRUB_TIMEOUT
  lineinfile:
    dest: /etc/default/grub
    state: present
    backup: yes
    regexp: '^GRUB_TIMEOUT=.*'
    line: 'GRUB_TIMEOUT=0'
  notify: update grub
  when: is_grub.stat.exists is defined and is_grub.stat.exists
  tags: master
