---
- hosts: localhost

  handlers:
    - import_tasks: handlers.yml

  pre_tasks:
    - name: Set the LED steady before upgrading !!!
      shell: echo default-on >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: always

    - name: disable dnsmasq to enable network operations
      shell: systemctl stop dnsmasq
      become: yes
      ignore_errors: yes
      tags: always

    - name: stop services using {{ data_path }}
      shell: systemctl stop kiwix edupi kalite aflatoun
      become: yes
      ignore_errors: yes
      tags: always

  roles:
    - role: variables

    - role: restore
      tags: move-content

    # master, setup (timezone, apt-update)
    - role: system

      # master, resize
    - role: resize

      # master, rename
    - role: nginx

    - role: home

    - role: uwsgi
      tags: master

      # master, rename, setup, reconfigure
    - role: dnsmasq
    - role: hostapd
    - role: iptables
    - role: network-manager

      # master, resize, rename
    - role: kiwix

    # master, rename (nginx hostname), reconfigure (password)
    - role: clock

      # master, rename
    - role: captive_portal

      # content setup (install, dependencies)
    - role: nomad_setup
      when: ansible_local.config.nomad|bool

    - role: mathews_setup
      when: ansible_local.config.mathews|bool

    - role: africatik_setup
      when: ansible_local.config.africatik|bool

    - role: africatikmd_setup
      when: ansible_local.config.africatikmd|bool

    - role: wikifundi_setup
      when: ansible_local.config.wikifundi_languages | length

    - role: aflatoun_setup
      when: ansible_local.config.aflatoun_languages | length

    - role: edupi_setup
      when: ansible_local.config.edupi|bool

    - role: kalite_setup
      when: ansible_local.config.kalite_languages | length

      # move content
    - role: edupi_content
      when: ansible_local.config.edupi_has_resources|bool

    - role: packages
      when: ansible_local.config.packages | length

    - role: kalite_content
      when: ansible_local.config.kalite_languages | length

    - role: aflatoun_content
      when: ansible_local.config.aflatoun_languages | length

    - role: wikifundi_content
      when: ansible_local.config.wikifundi_languages | length

    - role: backup
      tags: reconfigure

    - role: services
      tags: seal

  post_tasks:
    - name: disable services using {{ data_path }}
      shell: systemctl disable kiwix edupi kalite aflatoun
      become: yes
      ignore_errors: yes
      tags: ['master', 'resize']

    - name: Heartbeat mode on KoomBook LED, update is over !!!
      shell: echo heartbeat >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: ['always']
