---
- import_tasks: enable_service.yml
  vars:
    service: kiwix

- import_tasks: enable_service.yml
  vars:
    service: edupi
  when: ansible_local.config.edupi|bool

- import_tasks: enable_vhost.yml
  vars:
    name: edupi
  when: ansible_local.config.edupi|bool

- import_tasks: enable_service.yml
  vars:
    service: kalite
  when: ansible_local.config.kalite_languages | length

- import_tasks: enable_vhost.yml
  vars:
    name: kalite
  when: ansible_local.config.kalite_languages | length

- import_tasks: enable_service.yml
  vars:
    service: aflatoun
  when: ansible_local.config.aflatoun_languages | length

- import_tasks: enable_vhost.yml
  vars:
    name: aflatoun
  when: ansible_local.config.aflatoun_languages | length

- import_tasks: enable_service.yml
  vars:
    service: parsoid
  when: ansible_local.config.wikifundi_languages | length

- import_tasks: enable_service.yml
  vars:
    service: memcached
  when: ansible_local.config.wikifundi_languages | length

- import_tasks: enable_service.yml
  vars:
    service: php{{ php_version }}-fpm
  when: ansible_local.config.wikifundi_languages | length

- include_tasks: enable_vhost.yml
  vars:
    name: "{{ item }}.wikifundi"
  with_items: "{{ ansible_local.config.wikifundi_languages | default(omit) }}"
  when: ansible_local.config.wikifundi_languages | length

- import_tasks: enable_service.yml
  vars:
    service: dnsmasq

- import_tasks: disable_service.yml
  vars:
    service: rsyslog

- name: Disable SSH
  systemd:
    name: ssh
    enabled: no
