name: create master image
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: master image build
    runs-on: ubuntu-latest
    steps:

      - name: set image name
        run: echo ::set-env name=OUT_IMG::hotspot-master_$(echo $(date +%Y-%m-%d)).img

      - name: verify image name
        run : echo $OUT_IMG

      - name: decrypt SSH key
        env:
          ssh_key: ${{ secrets.ssh_key }}

        run: |
          echo "$ssh_key" | base64 -d > ssh_key
          chmod 600 ssh_key
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan download.kiwix.org >> ${HOME}/.ssh/known_hosts
          chmod 644 ${HOME}/.ssh/known_hosts

      - name: test upload
        run: |
          echo "from workflow" > test-file
          scp -i ssh_key test-file ci@download.kiwix.org:/data/tmp/ci/test-file

      - name: install system deps
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y locales openssh-client wget zip unzip tar python3-gi python3-gi-cairo python3-cairo gir1.2-gtk-3.0 libdbus-1-dev libdbus-glib-1-dev libffi-dev build-essential libssl-dev python3-dev libgdk-pixbuf2.0-dev

      - name: download custom kernel
        run: |
          wget http://mirror.download.kiwix.org/dev/vexpress-boot.zip
          unzip vexpress-boot.zip

      - name: download static Qemu
        run: |
          wget http://mirror.download.kiwix.org/dev/qemu-2.12.0-linux-x86_64.tar.gz
          tar xf qemu-2.12.0-linux-x86_64.tar.gz

      - name: download etcher-cli (packaging only)
        run: |
          wget http://download.kiwix.org/dev/balena-etcher-cli-1.4.8-linux-x64.tar.gz
          mkdir -p etcher-cli
          tar xf balena-etcher-cli-1.4.8-linux-x64.tar.gz -C etcher-cli --strip-components=1

      - name: download aria2c (packaging only)
        run: |
          wget http://download.kiwix.org/dev/aria2c-linux64.zip
          unzip aria2c-linux64.zip
          rm aria2c-linux64.zip
          wget http://download.kiwix.org/dev/ca-certificates.crt

      - name: setup python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-linux.txt
          pip install -U pyinstaller

      - name: compile app
        run: pyinstaller --log-level=DEBUG kiwix-hotspot-linux.spec

      - name: build master image
        run: dist/kiwix-hotspot image --ram 8G --root 7 --size 8 --out ${OUT_IMG}

      - name: ZIP master image
        run: zip -9 ${OUT_IMG}.zip ${OUT_IMG}

      - name: upload master image to kiwix server
        run: scp ${OUT_IMG}.zip ci@download.kiwix.org:/data/download/hotspots/base/
